# Generated by Django 4.1.7 on 2023-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('pw', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('v_code', models.CharField(max_length=500, unique=True)),
                ('v_status', models.CharField(max_length=500)),
            ],
        ),
    ]
