# Generated by Django 4.1.7 on 2023-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=500)),
                ('git', models.CharField(max_length=500)),
                ('fb', models.CharField(max_length=500)),
                ('linkedin', models.CharField(max_length=500)),
                ('pw', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
