# Generated by Django 4.1.7 on 2023-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='facts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('no_of_client', models.CharField(max_length=500)),
                ('no_of_project', models.CharField(max_length=500)),
                ('no_of_hours', models.CharField(max_length=500)),
                ('no_of_hardworkers', models.CharField(max_length=500)),
            ],
        ),
    ]
